### ISSUE TITLE
Darkorbit X-2 Map bot flees to middle gate jumping to 4-4 and then dies

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#73] opened 2019-04-09 19:59 UTC
**Describe the bug**
X-2 Map bot flees to middle gate jumping to 4-4 and then dies
**only on spaceball event!**

**To Reproduce**
Have the bot flee on X-2 map when spaceball is on.

**Expected behavior**
Bot should only flee to the 3 outside gates not the middle one.

**Screenshots**
![Desktop Screenshot 2019 04 09 - 21 57 00 34](https://user-images.githubusercontent.com/45576830/55831141-ba9e8280-5b12-11e9-9404-5538b05ce7e5.png)

**Additional context**
-

**Comment by crashblaster** [comment] 2019-04-10 00:15
*irony on* That is not a bug its a feature ^^ The bot is collecting some nice spaceball bonus boxes :D *irony off*

**Comment by crashblaster** [comment] 2019-04-11 22:41
should be fixed with these two updates:
 v4.0.18.8-1: DO: Won't fly into gates in the center
 v4.0.18.8-1: DO: Won't flee to 4-4

**Comment by crashblaster** [comment] 2019-04-29 22:12
reopen because guys have responded that this bug still exists on discord

**Comment by BottingMarket** [comment] 2019-04-29 22:25
Yes I can confirm it still happened when spaceball event is on it jumps the middle gate in the X-2 Maps

**Comment by crashblaster** [comment] 2019-06-20 17:31
should be fixed now:
Update v4.25
- DO: fix: Won't jump through spaceball gate

**Closed by crashblaster** 2019-06-20 17:31 UTC
Labels: DarkOrbit, Important, bug
