### ISSUE TITLE
Bot Flee to X-8 Map base

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#61] opened 2019-03-29 14:02 UTC
**Is your feature request related to a problem? Please describe.**
It would be great if the bot would see the X-8 base as a safe zone. So when it's close it will also flee to the base, instead fleeing to a Base that's much further away.

**Describe the solution you'd like**
Also flee to X-8 Base.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by berkeleyinc** [comment] 2019-03-29 14:37
Duplicate of https://github.com/berkeleyinc/Golem/issues/7

**Closed by berkeleyinc** 2019-03-29 14:37 UTC
Labels: DarkOrbit, enhancement
