### ISSUE TITLE
No Config change, New Gate X-8 stuck

### ISSUE THREAD

**Issue by iNSOMNiA3D** [berkeleyinc/Golem#21] opened 2018-12-06 14:59 UTC
**Describe the bug**
Bot is not changing config to flee when it is set to. Flees often to new gate in x8 and gets stuck

**To Reproduce**
get an enemy to come into map and be close by or, attack new npc's in x8 so hp and shield go well below repair levels

**Expected behavior**
Expected to swap to config 2 and run for port then to repair once safe.

**Additional context**
Only noticed this today so can not give any further info at present.
this is in standard kill npc mode not task bot.
Temporaryt fix against new npc i have listed only the streuners in order to aviod the dmg.

**Comment by berkeleyinc** [comment] 2018-12-06 15:03
duplicate of https://github.com/berkeleyinc/Golem/issues/19

**Closed by berkeleyinc** 2018-12-06 15:03 UTC
Labels: DarkOrbit, bug, duplicate
