### ISSUE TITLE
CBS Stuck

### ISSUE THREAD

**Issue by iNSOMNiA3D** [berkeleyinc/Golem#24] opened 2018-12-07 21:51 UTC
**Describe the bug**
Bot stuck near CBS with "Avoid Clan Bases" option enabled

**Screenshots**
https://cdn.discordapp.com/attachments/519622833492590623/520692431637970954/unknown.png

**Additional context**
23:02:33 [info] Select '-=[ Lordakia ]=-'.
23:02:33 [trace] 0BB955 1BB942 2BB955 tick=40
23:02:33 [info] Select '-=[ Lordakia ]=-'.
23:02:33 [info] Attack '-=[ Lordakia ]=-'.
23:02:33 [info] NPC '-=[ Lordakia ]=-' killed.
23:02:34 [info] Earned 800 Cre. (total 19200)
23:02:34 [info] Earned 2 Uri. (total 32)
23:02:34 [info] Select '-=[ Mordon ]=-'.
23:02:34 [trace] 0BB955 1BB955 2BB955 tick=40
23:02:34 [info] Select '-=[ Mordon ]=-'.
23:02:34 [info] Attack '-=[ Mordon ]=-'.
23:02:37 [info] Threat recognized CBS
23:02:37 [trace] 0BB955 1BB955 2BB1593 tick=40
23:02:39 [info] NPC '-=[ Mordon ]=-' killed.
23:02:39 [info] Earned 6400 Cre. (total 25600)
23:02:39 [info] Earned 8 Uri. (total 40)
23:02:39 [info] Threat recognized CBS
23:02:39 [trace] 0BB1593 1BB955 2BB1593 tick=74
23:02:41 [info] Threat recognized CBS
23:02:41 [trace] 0BB1593 1BB1593 2BB1593 tick=40
23:02:45 [info] Threat recognized CBS
23:02:46 [trace] 0BB1593 1BB1593 2BB1593 tick=180
23:02:47 [info] Threat recognized CBS
23:02:51 [info] Threat recognized CBS
23:02:51 [trace] 0BB1593 1BB1593 2BB1593 tick=95
23:02:53 [info] Threat recognized CBS
23:02:55 [info] Threat recognized CBS
23:02:56 [trace] 0BB1593 1BB1593 2BB1593 tick=40
23:02:57 [info] Threat recognized CBS
23:02:59 [info] Threat recognized CBS
23:03:01 [trace] 0BB1593 1BB1593 2BB1593 tick=40
23:03:01 [info] Threat recognized CBS
23:03:05 [info] Threat recognized CBS
23:03:06 [trace] 0BB1593 1BB1593 2BB1593 tick=40
23:03:07 [info] Threat recognized CBS

**Comment by berkeleyinc** [comment] 2018-12-09 12:46
thats a duplicate of https://github.com/berkeleyinc/Golem/issues/22

**Closed** 2018-12-09 13:04 UTC
Labels: DarkOrbit, bug, duplicate
