### ISSUE TITLE
BL Map X-7 - X-8 Gate problem 

### ISSUE THREAD

**Issue by iNSOMNiA3D** [berkeleyinc/Golem#19] opened 2018-12-06 14:52 UTC
**Describe the bug**
The bot thinks that the portal to BL map is the way to go x-7

**To Reproduce**
Put your bot in x-7 , Wait until he flee in x-8 and u will see that he will do x-8 to BL map even if hej ust jumped from x-7 to x-8

**Expected behavior**
I expected the bot to go from x-8 to x-7 :)

**Screenshots**
https://cdn.discordapp.com/attachments/519622833492590623/520202759774142485/unknown.png

**Comment by berkeleyinc** [comment] 2018-12-06 15:04
duplicate of https://github.com/berkeleyinc/Golem/issues/16

**Closed by berkeleyinc** 2018-12-06 15:04 UTC
Labels: DarkOrbit, bug, duplicate
